### ISSUE TITLE
Can't upload

### ISSUE THREAD

**Issue by Kori-no-Otoko** [CodeTNMaryville/ForgetMeNot#1]
It says I need a push request to upload a file...

**Comment by ghost** [comment]
Just made everyone from member to owner. Try now

**Comment by Kori-no-Otoko** [comment]
Do you want us to commit to the master branch or a new branch?

**Comment by ghost** [comment]
When you re-upload just do it to the master branch. Just rename the file
ForgetMeNot v0.1, ForgetMeNot v0.2, etc.
